name: Merge PR

on: workflow_call

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: false

    - name: Vulnerability management
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...


