name: CI - golang
on:
  workflow_call:
    inputs:
      ignore_copyright:
        required: false
        type: string
      test_folder:
        required: false
        type: string
      short_test:
        required: false
        type: string
      ignore_build: 
        required: false
        type: string
      go_race:    
        required: false
        type: string
    secrets:
      reporeading_token:
        required: true
      codecov_token:
        required: false
      chargebee_token:
        required: true
      chargebee_sitename:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
        cache: false

    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Check pull request file size
      if: github.event_name == 'pull_request'
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/checkPR.sh | bash 
      env: 
        token: ${{ secrets.reporeading_token }}
        pr_number: ${{ github.event.number }}

    - name: CI
      uses: untillpro/ci-action@master
      with:
        ignore: ${{ inputs.ignore_copyright }}
        codecov-go-race: ${{ inputs.go_race }}
        organization: 'untillpro,heeus'
        token: ${{ secrets.reporeading_token }}
        codecov-token: ${{ secrets.codecov_token }}
        short-test:  ${{ inputs.short_test }}
        ignore-build:  ${{ inputs.ignore_build }}
        run-mod-tidy: false
      env:
        CHARGEBEE_PUBLISHABLE_KEY: ${{ secrets.chargebee_token }}
        CHARGEBEE_SITE_NAME: ${{ secrets.chargebee_sitename }}

    - name: Upload project
      uses: actions/upload-artifact@v4
      with:
        name: project-files
        path: .

#    - name: Archive Go modules cache        
#      uses: actions/upload-artifact@v4
#      with:
#        name: go-mod-cache
#        path: | 
#           ~/go/pkg/mod

#    - name: Archive Go modules cache        
#      uses: actions/upload-artifact@v4
#      with:
#        name: go-cache
#        path: | 
#          ~/.cache/go-build           
              
    - name: Check copyright
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/check_copyright.sh | bash -s "$(go env GOPATH)"

    - name: Linters
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/gbash.sh | bash -s "$(go env GOPATH)"
