name: CI - golang
on:
  workflow_call:
    inputs:
      ignore_copyright:
        required: false
        type: string
    secrets:
      reporeading_token:
        required: true
      codecov_token:
        required: true
      personal_token:	
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Go - Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: CI
      uses: untillpro/ci-action@master
      with:
        ignore: ${{ inputs.ignore_copyright }}
        organization: 'untillpro, heeus'
        token: ${{ secrets.reporeading_token }}
        codecov-token: ${{ secrets.codecov_token }}

    - name: Check copyright
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/check_copyright.sh | bash -s "$(go env GOPATH)"

    - name: Linters
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/gbash.sh | bash -s "$(go env GOPATH)"

    - name: Rebuild airs-bp3
      if: ${{ (github.event_name == 'push') && (github.ref != 'refs/heads/rc' && github.ref != 'refs/heads/release' && github.ref != 'refs/heads/rcfix') }}
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/rebuild-test-bp3.sh | bash
      env: 
        github_token: ${{ secrets.reporeading_token }}
        gh_event: ${{ github.event_name }}

    - name: Push changes to pb3
      if: ${{ (contains(github.repositoryUrl, 'heeus' ) || contains(github.repositoryUrl, 'untillpro' )) &&
        github.event_name == 'push' &&  (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
      uses: actions-js/push@master
      with:
        directory: ../../${{ github.event.repository.name }}/airs-bp3
        repository: untillpro/airs-bp3
        message: "Update repo airs-bp3"
        branch: "main"
        github_token: ${{ secrets.personal_token }}

