name: CI - golang
on:
  workflow_call:
    inputs:
      ignore_copyright:
        required: false
        type: string
    secrets:
      reporeading_token:
        required: true
      codecov_token:
        required: true
      chargebee_token:
        required: true
      chargebee_sitename:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Go - Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: CI
      uses: untillpro/ci-action@master
      with:
        ignore: ${{ inputs.ignore_copyright }}
        organization: 'untillpro, heeus'
        token: ${{ secrets.reporeading_token }}
        codecov-token: ${{ secrets.codecov_token }}
      env:
        CHARGEBEE_PUBLISHABLE_KEY: ${{ secrets.chargebee_token }}
        CHARGEBEE_SITE_NAME: ${{ secrets.chargebee_sitename }}
        HEEUS_SKIP_SLOW_TESTS: 0

    - name: Check copyright
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/check_copyright.sh | bash -s "$(go env GOPATH)"

    - name: Linters
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/gbash.sh | bash -s "$(go env GOPATH)"

