name: CI - node
on:
  workflow_call:
    inputs:
      ignore_copyright:
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Check pull request file size
      if: github.event_name == 'pull_request'
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/checkPR.sh | bash
      env: 
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        pr_number: ${{ github.event.number }}

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        git config --global url."https://".insteadOf ssh://

    - name: Cache Node - npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: CI
      uses: untillpro/ci-action@master
      with:
        ignore: ${{ inputs.ignore_copyright }}
        organization: 'untillpro'

